### ISSUE TITLE
请问这个是只针对Outsider mod还是针对游戏本体

### ISSUE THREAD

**Issue by solitary-sails** [nice2cu1/OuterWildFixFont#1]
如题

**Comment by nice2cu1** [comment]
该补丁对[DialogueBoxVer2类的InitializeFont方法](https://github.com/nice2cu1/OuterWildFixFont/blob/009a19d5cb52ff852cde2b1154ed2a506f3a6060/OuterWildFixFont/OuterWildFixFont.cs#L67)以及[NomaiTranslatorProp类的InitializeFont方法进行了重写](https://github.com/nice2cu1/OuterWildFixFont/blob/009a19d5cb52ff852cde2b1154ed2a506f3a6060/OuterWildFixFont/OuterWildFixFont.cs#L101)，将languageFont替换为了自行加载的AssetBundle字体包，并没有对mod进行修补。
所以可以理解为这是针对于整个游戏的补丁。
但事实上，该补丁并不是对原作者的mod进行修补，而是[经我简单翻译过后的mod](https://github.com/nice2cu1/Outer-Wilds-The-Outsider)做出的修补。
New Horizons或许有更好的办法来解决故事模组中文字体不全的方法，但我并没有了解过，该仓库是退而求次且省时的办法。

**Comment by solitary-sails** [comment]
原来如此，才发现您原来有一个汉化后的分支。说起来我和一个星际拓荒的交流群里的朋友们总抱怨官方的缺字和翻译错误，奈何没编程能力来解决问题。如果您以后有翻译别的模组的计划，需要帮忙翻译文本的话可以来群里寻找愿意帮忙的朋友。QQ群号：916462960

**Comment by nice2cu1** [comment]
你的意思是基于 New Horizons 的故事 mod 也存在中文字体缺失的情况？如果是，我认为应该向New Horizons 发起 issue报告错误。另外，Q 群已加入。
