### ISSUE TITLE
Adding this mod to the database

### ISSUE THREAD

**Issue by xen-42** [nice2cu1/OuterWildFixFont#2]
I have some requests before this is added to the database.

Can you update the "about" line to explain the mod better? Right now it says "针对Outer-Wilds-The-Outsider的补丁" but from the readme it sounds like the mod isn't just for The Outsider anymore.

Can you also add a single line in English explaining what the mod does in the description? It's useful for us so we can see what all the different mods on the database are doing.

Thank you!

**Comment by nice2cu1** [comment]
I have used a translator to update the English description.
