### ISSUE TITLE
安装此mod后飞船内信号镜文字特别小

### ISSUE THREAD

**Issue by ST-Chara** [nice2cu1/OuterWildFixFont#4]
经测试，如果使用HYSongYunLangHeiW可以正常显示

**Comment by nice2cu1** [comment]
@ST-Chara 目前我的电脑上没有开发环境，欢迎pr。我大概会在下一个节假日期间发布修复。

**Comment by nice2cu1** [comment]
已经连夜部署环境，修复了该问题。信号镜文字的问题是因为我的疏忽导致object没有被找到。

**Comment by nice2cu1** [comment]
[Release v2.0.4](https://github.com/nice2cu1/OuterWildFixFont/releases/tag/2.0.4)

**Comment by nice2cu1** [comment]
@ST-Chara  你好，我发现我目前的办法（v2.0.4）只是在临时解决问题，在飞船信号镜中文字仍然会有缺失，我看你提起过HYSongYunLangHeiW可以正常显示大小，于是我做了尝试，但似乎不起作用？你可以告知我你的测试方法吗，非常感谢！
![image](https://github.com/nice2cu1/OuterWildFixFont/assets/33564254/1df1a3c3-fa8c-474a-a752-9febb72a1e82)

**Comment by nice2cu1** [comment]
[Release v2.0.6(https://github.com/nice2cu1/OuterWildFixFont/releases/tag/2.0.6)
